name: SerenityBDD CI

on:
  workflow_dispatch:

jobs:
  run-serenity:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Instalar Google Chrome
        run: |
          sudo apt update
          sudo apt install -y wget gnupg2
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt update
          sudo apt install -y google-chrome-stable
          echo "CHROME_BIN=/usr/bin/google-chrome" >> $GITHUB_ENV

      - name: Ejecutar pruebas Serenity con Chrome Headless
        run: |
          mvn clean verify -Dwebdriver.driver=chrome -Dchrome.options="--headless"

      - name: Publicar reporte Serenity
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity
